'use client';
import Image from 'next/image';
import Link from 'next/link';
import { ArrowUpRight, ArrowLeft, ArrowRight, Phone, MessageCircle } from 'lucide-react';
import { experienceCopy as copy, showroomConfig as tour, siteConfig } from '@/config/site';

export interface ChapterContentProps {
 index:number;service:number;setService:(value:number)=>void;category:number;setCategory:(value:number)=>void;comparison:number;setComparison:(value:number)=>void;step:number;setStep:(value:number)=>void;project:number;setProject:(value:number)=>void;openGallery:()=>void;openService:()=>void;
}
export default function ChapterContent({index,service,setService,category,setCategory,comparison,setComparison,step,setStep,project,setProject,openGallery,openService}:ChapterContentProps){
 const item=siteConfig.portfolio[project];
 if(index===0)return <div className="action-row"><Link href="/contact" className="primary-action">{tour.quote}<ArrowUpRight size={18}/></Link><Link href="/work" className="text-action">{tour.explore}<ArrowUpRight size={17}/></Link></div>;
 if(index===1)return <div className="category-showcase"><div className="category-selector" role="group" aria-label={tour.chapterLabel}>{copy.categories.map((name,i)=><button key={name} aria-pressed={category===i} onClick={()=>setCategory(i)}><span>0{i+1}</span>{name}<ArrowUpRight size={16}/></button>)}</div><p className="selection-description" aria-live="polite">{copy.categoryDescriptions[category]}</p></div>;
 if(index===2)return <div className="service-showcase"><div className="service-selector" role="group" aria-label={copy.chooseService}>{tour.services.map((item,i)=><button key={item.id} aria-pressed={i===service} onClick={()=>setService(i)}>{item.title}</button>)}</div><div className="service-detail" aria-live="polite"><span className="detail-label">{tour.services[service].tag}</span><p>{tour.services[service].detail}</p><div className="action-row"><button className="text-action inspect-action" onClick={openService}>{copy.inspect}<ArrowUpRight size={16}/></button><Link className="text-action" href={`/contact?service=${tour.services[service].id}`}>{tour.serviceCta}<ArrowUpRight size={16}/></Link></div></div></div>;
 if(index===3)return <div className="transformation-control"><div className="comparison-labels"><span>{copy.before}</span><span>{copy.after}</span></div><input type="range" min="0" max="100" step="1" value={comparison} aria-label={copy.comparison} onChange={e=>setComparison(Number(e.target.value))}/><p className="comparison-note">{copy.comparisonNote}</p><Link href="/contact?service=acp-cladding" className="text-action">{siteConfig.transformation.ctaText}<ArrowUpRight size={17}/></Link></div>;
 if(index===4)return <div className="craft-list">{siteConfig.whyUs.map((item,i)=><details key={item.number}><summary><span>0{i+1}</span>{item.title}<span className="detail-plus">+</span></summary><p>{item.description}</p></details>)}</div>;
 if(index===5)return <div className="project-preview"><button onClick={openGallery} className="project-image" aria-label={`${copy.viewImage}: ${item.title}`}><Image src={item.image} alt={item.title} fill sizes="(max-width: 767px) 85vw, 430px" className="object-cover"/><span className="image-expand"><ArrowUpRight size={21}/></span></button><div className="project-meta"><span>{item.category}</span><div className="gallery-controls"><button aria-label={copy.previous} onClick={()=>setProject((project+siteConfig.portfolio.length-1)%siteConfig.portfolio.length)}><ArrowLeft size={17}/></button><span>{String(project+1).padStart(2,'0')} / {String(siteConfig.portfolio.length).padStart(2,'0')}</span><button aria-label={copy.next} onClick={()=>setProject((project+1)%siteConfig.portfolio.length)}><ArrowRight size={17}/></button></div></div><p className="reference-label">{project===5?copy.pages.about.facilityCaption:copy.reference}</p><Link href="/work" className="text-action">{copy.galleryAction}<ArrowUpRight size={16}/></Link></div>;
 if(index===6)return <div className="process-showcase"><div className="process-selector" role="group" aria-label={tour.chapters[6].label}>{siteConfig.process.map((item,i)=><button key={item.step} aria-pressed={step===i} onClick={()=>setStep(i)}><span>{item.step}</span><i/></button>)}</div><div className="process-detail" aria-live="polite"><h3>{siteConfig.process[step].title}</h3><p>{siteConfig.process[step].description}</p></div></div>;
 return <div className="final-actions"><div className="action-row"><Link href="/contact" className="primary-action">{tour.quote}<ArrowUpRight size={18}/></Link><a className="text-action" href={`tel:+91${siteConfig.contact.phone1.raw}`}><Phone size={15}/>{copy.call}</a><a className="text-action" href={siteConfig.contact.whatsappLink} target="_blank" rel="noopener noreferrer"><MessageCircle size={16}/>{copy.whatsapp}</a></div><p className="final-contact">{siteConfig.contact.phone1.display}<span>{siteConfig.contact.address}</span></p></div>;
}
