'use client';
import { useId, useState } from 'react';
import { ArrowUpRight } from 'lucide-react';
import { experienceCopy, siteConfig } from '@/config/site';
import { buildEnquiryUrl, resolveService } from '@/lib/enquiry';
export default function QuoteForm({initialService=''}:{initialService?:string}){
 const uid=useId(),copy=experienceCopy.form;
 const [data,setData]=useState({name:'',phone:'',service:resolveService(initialService),dimensions:'',message:''});
 const change=(field:keyof typeof data,value:string)=>setData({...data,[field]:value});
 const submit=(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();const submitter=(event.nativeEvent as SubmitEvent).submitter;const email=submitter?.getAttribute('value')==='email';window.open(buildEnquiryUrl(data,email?'email':'whatsapp'),'_blank','noopener,noreferrer');};
 return <form onSubmit={submit} className="quote-form"><div className="form-pair"><label htmlFor={`${uid}-name`}>{copy.name}<input id={`${uid}-name`} name="name" autoComplete="name" required maxLength={100} value={data.name} onChange={e=>change('name',e.target.value)} placeholder={copy.namePlaceholder}/></label><label htmlFor={`${uid}-phone`}>{copy.phone}<input id={`${uid}-phone`} name="phone" type="tel" inputMode="tel" autoComplete="tel" required pattern="[+0-9 \-]{7,20}" maxLength={20} value={data.phone} onChange={e=>change('phone',e.target.value)} placeholder={copy.phonePlaceholder}/></label></div><label htmlFor={`${uid}-service`}>{copy.service}<select id={`${uid}-service`} name="service" value={data.service} onChange={e=>change('service',e.target.value)}><option value={experienceCopy.fullService}>{experienceCopy.fullService}</option>{siteConfig.coreServices.map(service=><option key={service.id} value={service.title}>{service.title}</option>)}</select></label><label htmlFor={`${uid}-dimensions`}>{copy.dimensions}<input id={`${uid}-dimensions`} name="dimensions" maxLength={120} value={data.dimensions} onChange={e=>change('dimensions',e.target.value)} placeholder={copy.dimensionsPlaceholder}/></label><label htmlFor={`${uid}-message`}>{copy.message}<textarea id={`${uid}-message`} name="message" rows={4} maxLength={1500} value={data.message} onChange={e=>change('message',e.target.value)} placeholder={copy.messagePlaceholder}/></label><div className="action-row"><button type="submit" value="whatsapp" className="primary-action">{copy.submit}<ArrowUpRight size={18}/></button><button type="submit" value="email" className="text-action">{copy.email}</button></div><p className="form-note">{copy.note}</p></form>
}
